site_name: 大富翁量化社区

nav:
  - 简介: index.md
  - 新手指南: getting_started.md
  - 大富翁量化交易教程: tutorial.md
  - 大富翁量化框架深度解析: developer_guide.md
  - 关于大富翁:
    - 授权许可: license.md
    - 版本历史: history.md
    - 关于开发者: authors.md
  - 社区: https://github.com/zillionare/zillionare/discussions
  - 链接:
    - 知乎专栏: https://www.zhihu.com/column/jieyu
    - readthedocs: https://zillionare.readthedocs.io/zh_CN/latest/contributing.html

theme:
  name: material

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - include-markdown
  - search:
      lang: ja
