site_name: 欢迎加入大富翁量化交易社区！

nav:
  - 简介: index.md
  - 新手教程 : tutorial.md
  - 社区: https://zillionare.readthedocs.io/zh_CN/latest/contributing.html
  - 版本历史: history.md
  - 开发者指南: developer_guide.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - include-markdown
  - search:
      lang: ja
