site_name: 解语科技
site_url: http://www.jieyu.ai
repo_url: https://github.com/zillionare/zillionare
repo_name: zillionare
#strict: true

theme:
  name: material
  language: zh
  logo: assets/logo.png
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - mknotebooks
  - search:
      lang: ja
  - awesome-pages
extra:
  social:
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/club/1243142164264886272
      name: 知乎圈子
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/cgi-bin/qm/qr?k=kErrI22lCmhKXN8we_iY7jS2sBPnXk8_&jump_from=webapi
      name: 量化交易群
    - icon: fontawesome/brands/github
      link: https://github.com/zillionare
      name: Github
    - icon: material/email
      link: "mailto:code@jieyu.ai"
  disqus: jieyu
google_analytics:
  - UA-27842639-4
  - auto