# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: [ master, main, release ]
  pull_request:
    branches: [ master, main, release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      POSTGRES_DB: zillionare
      POSTGRES_HOST: localhost
      POSTGRES_USER: zillionare
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: zillionare
      JQ_ACCOUNT: "${{secrets.JQ_ACCOUNT}}"
      JQ_PASSWORD: ${{secrets.JQ_PASSWORD}}
      POSTGRES_ENABLED: true
      INIT_BARS_MONTHS: 1
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        run: make test

      - name: list files
        run: ls -l .
