# This is a basic workflow to help you get started with Actions

name: build & release

# Controls when the action will run.
on:
  push:
    branches: release
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      JQ_ACCOUNT: "${{secrets.JQ_ACCOUNT}}"
      JQ_PASSWORD: ${{secrets.JQ_PASSWORD}}
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      PYPI_INDEX_URL: https://pypi.org/simple
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build installer
        run: make dist

      - name: list files
        run: |
          ls -l .
          ls -l docs/download

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: build docs
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements_dev.txt
          mkdocs build

      - name: publish documentation/site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site

      - name: create github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            docs/download/*.sh
            docs/download/*.tar.gz
          draft: true
          prerelease: true
